# permissions for end users to view gitpods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitpod-viewer-role
rules:
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods/status
  verbs:
  - get
