---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods/finalizers
  verbs:
  - update
- apiGroups:
  - gitpod.gitpod.io
  resources:
  - gitpods/status
  verbs:
  - get
  - patch
  - update
